### ISSUE TITLE
sim.plot2D aborts with "RuntimeError: meep: meep: Matrix is singular, aborting." when using geometry_center

### ISSUE THREAD

**Issue by mfgburger** [NanoComp/meep#1335]
When using the geometry_center argument, sim.plot2D sometimes aborts for no obvious reason and the exception "RuntimeError: meep: meep: Matrix is singular, aborting." is raised.

A code example that's based on the Simpetus grating coupler example can be found here: https://pastebin.com/tvZsKazm

Weirdly, it also depends on the exact geometry, e.g. exactly how many rings the grating has, whether the issue occurs or not.

**Comment by oskooi** [comment]
The problem is that the `size` of the `output_plane` parameter in `plot2D` of your script has infinite dimensions (i.e., `mp.inf`). 

This should be fixed to finite dimensions which will produce the correct output:

```py
xzplane = mp.Block(center=mp.Vector3(0,0,0), size=mp.Vector3(cell_size.x,0,cell_size.z))
xyplane = mp.Block(center=mp.Vector3(0,0,0), size=mp.Vector3(cell_size.x,cell_size.y,0))
```

![plot2D](https://user-images.githubusercontent.com/7152530/91741533-b80a5600-eb69-11ea-9e50-9e98132d07b7.png)

**Comment by mfgburger** [comment]
Thank you for the quick reply! 

Unfortunately, the issue persists, even after I have implemented the changes you suggested. For N=1 and N=7 e.g. plotting still aborts with the same exception.

Also, is it normal that the PML layer on the right is cut off in the plot that you've attached above?

**Comment by oskooi** [comment]
Seems that the `geometry_center=mp.Vector3(N*a/2,0,0)` that you added to the `Simulation` constructor in your script is the cause of the problem. Remove that line and the results are as expected.

**Comment by smartalecH** [comment]
I think the issue though is @mfgburger *wants* to move the simulation domain over *and* visualize it.

This seems like a bug in the `complex_array_slice routine` (rather than `plot2D`). Worth investigating.

**Comment by abdelix** [comment]
I have encountered the same Issue. As @smartalecH  suggests it crashes in complex_array_slice . One workaround that worked for me is to manually specify the frequency as 0 when calling plot2D.

```python
sim.plot2D(ax=ax, output_plane=cell, frequency=0)
```

**Comment by Chuban** [comment]
I had the same issue. Setting `frequency=0` in `plot2D` fixed the issue.
