### ISSUE TITLE
meep 1.12, '__swig_getmethods__' is not defined

### ISSUE THREAD

**Issue by pekermilas** [NanoComp/meep#1436]
Hi guys,

I am trying to run meep 1.12 on ubuntu 20.04 subsystem. When I try to import meep within ipython3, I kept getting this error
message; 

NameError: name '__swig_getmethods__' is not defined

I have Python3.8.5 and Swig 4.0.1. I have no idea what is going on with this configuration. Can you please help me on that?

Thanks

**Comment by stevengj** [comment]
This was fixed by #1159, so you should just need to upgrade to a newer Meep version.

**Comment by pekermilas** [comment]
With all do respect,
 
This is not fixed, actually it is not even close to get fixed. The software version you provide here is 1.16 and Ubuntu repositories have only 1.12. This is going to be every user's problem unless you keep the version in Ubuntu repositories up-to-date. Or at least, warn your users about it. 

Thanks
Peker Milas, PhD

**Comment by stevengj** [comment]
We don't maintain the Ubuntu packages.  You should file an Ubuntu issue for them to update Meep:  https://help.ubuntu.com/community/ReportingBugs

**Comment by stevengj** [comment]
It looks like Debian unstable already has Meep 1.16, so that should eventually propagate to Ubuntu: https://packages.debian.org/search?keywords=meep
